INSERT INTO users (name, age) VALUES ("reid", 36);
INSERT INTO users (name, age) VALUES ("reid", 36);
INSERT INTO users (name, age) VALUES ("reid", 36);
INSERT INTO users (name, age) VALUES ("reid", 36);
INSERT INTO users (name, age) VALUES ("reid", 36);
INSERT INTO users (name, age) VALUES ("reid", 36);
INSERT INTO users (name, age) VALUES ("reid", 36);
INSERT INTO users (name, age) VALUES ("reid", 36);
INSERT INTO users (name, age) VALUES ("reid", 36);
INSERT INTO users (name, age) VALUES ("reid", 36);
INSERT INTO users (name, age) VALUES ("reid", 36);
INSERT INTO users (name, age) VALUES ("reid", 36);
INSERT INTO users (name, age) VALUES ("reid", 36);
INSERT INTO users (name, age) VALUES ("reid", 36);
INSERT INTO users (name, age) VALUES ("reid", 36);
INSERT INTO users (name, age) VALUES ("reid", 36);
INSERT INTO users (name, age) VALUES ("reid", 36);
INSERT INTO users (name, age) VALUES ("reid", 36);
INSERT INTO users (name, age) VALUES ("reid", 36);
INSERT INTO users (name, age) VALUES ("reid", 36);


INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("First Project", "Community", 10, "10-01-2016", "10-05-2016");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Second Project", "Self", 100, "08-01-2015", "08-05-2015");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Third Project", "Community", 20, "07-01-2015", "07-05-2015");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Fourth Project", "Charity", 50, "06-01-2015", "06-05-2015");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Fifth Project", "Self", 100, "05-01-2015", "05-05-2015");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Sixth Project", "Self", 1000, "04-01-2015", "04-05-2015");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Seventh Project", "Charity", 80, "03-01-2015", "03-05-2015");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Eighth Project", "Community", 100, "02-01-2015", "02-05-2015");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Ninth Project", "Community", 200, "01-01-2015", "01-05-2015");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Tenth Project", "Community", 5000, "11-01-2015", "11-05-2015");

INSERT INTO pledges (amount, user_id, project_id) VALUES ( 10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 10, 3, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 10, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 20, 3, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 20, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 20, 4, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 30, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 30, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 30, 5, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 30, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 30, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 45, 4, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 45, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 45, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 45, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 50, 3, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 50, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 50, 4, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 50, 3, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 60, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 60, 4, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 60, 5, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 60, 1, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 75, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 75, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 75, 1, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 75, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 80, 5, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 80, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES ( 80, 5, 1);
